# Mustererkennung/Machine Learning - Assignment 8



In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits
%matplotlib inline

In [2]:
data = pd.read_csv("iris.data", header=None)
data.head(n=5)

0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

## Excercise 1. Perceptron

#### Splitting the data into training/test and according to their class memberships

In [3]:
"""X_train, X_test, y_train, y_test = train_test_split(data[list(range(4))], data[4], test_size=0.2, random_state=None)

X_train, y_train = X_train.to_numpy(), y_train.to_numpy()
X_test, y_test = X_test.to_numpy(), y_test.to_numpy()

print(y_train)

X_train_s = X_train[y_train=='Iris-setosa']
y_train_s = np.ones((X_train_s.shape[0], ))

X_test_s = X_test[y_test=='Iris-setosa']
y_test_s = np.ones((X_test_s.shape[0], ))

X_train_vv = X_train[np.equal(y_train=='Iris-versicolor', y_train=='Iris-virginica')]
y_train_vv = np.zeros((X_train_vv.shape[0], ))

X_test_vv = X_test[np.equal(y_test=='Iris-versicolor', y_test=='Iris-virginica')]
y_test_vv = np.zeros((X_test_vv.shape[0], ))

shuffle_idx = np.random.permutation(X_train_s.shape[0])
X_train_s, y_train_s = X_train_s[shuffle_idx], y_train_s[shuffle_idx]

X_train, y_train = np.vstack((X_train_s, X_train_vv)), np.hstack((y_train_s, y_train_vv))
X_test, y_test = np.vstack((X_test_s, X_test_vv)), np.hstack((y_test_s, y_test_vv))

shuffle_idx = np.random.permutation(X_train.shape[0])
X_train, y_train = X_train[shuffle_idx], y_train[shuffle_idx]
"""

"""x, y = load_digits(return_X_y=True)

x = x.reshape((-1, 8 * 8))

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=None, stratify=y)"""

'x, y = load_digits(return_X_y=True)\n\nx = x.reshape((-1, 8 * 8))\n\nX_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=None, stratify=y)'

In [4]:
"""X_train, X_test, y_train, y_test = train_test_split(data[list(range(4))], data[4], test_size=0.2, random_state=None, stratify=data[4])

X_train_setosa = X_train[y_train=='Iris-setosa'].to_numpy()
X_train_versicolor = X_train[y_train=='Iris-versicolor'].to_numpy()
X_train_virginica = X_train[y_train=='Iris-virginica'].to_numpy()

X_test_s = X_test.to_numpy()
y_test_s = (y_test == 'Iris-setosa').astype(int).to_numpy()

X_test_vv = X_test[y_test!='Iris-setosa'].to_numpy()
y_test_vv = (y_test[y_test!='Iris-setosa'] == 'Iris-versicolor').astype(int).to_numpy()

X_train_vv = np.vstack((X_train_versicolor, X_train_virginica))
y_train_vv = np.zeros((X_train_vv.shape[0], ))
X_train_s = X_train_setosa
y_train_s = np.ones((X_train_setosa.shape[0], ))

X_test_vv = np.vstack((X_train_versicolor, X_train_virginica))

X_train = np.vstack((X_train_vv, X_train_s))
y_train = np.hstack((y_train_vv, y_train_s))

X_test = np.vstack((X_test_vv, X_test_s))
y_test = np.hstack((y_train_vv, y_train_s))"""

"X_train, X_test, y_train, y_test = train_test_split(data[list(range(4))], data[4], test_size=0.2, random_state=None, stratify=data[4])\n\nX_train_setosa = X_train[y_train=='Iris-setosa'].to_numpy()\nX_train_versicolor = X_train[y_train=='Iris-versicolor'].to_numpy()\nX_train_virginica = X_train[y_train=='Iris-virginica'].to_numpy()\n\nX_test_s = X_test.to_numpy()\ny_test_s = (y_test == 'Iris-setosa').astype(int).to_numpy()\n\nX_test_vv = X_test[y_test!='Iris-setosa'].to_numpy()\ny_test_vv = (y_test[y_test!='Iris-setosa'] == 'Iris-versicolor').astype(int).to_numpy()\n\nX_train_vv = np.vstack((X_train_versicolor, X_train_virginica))\ny_train_vv = np.zeros((X_train_vv.shape[0], ))\nX_train_s = X_train_setosa\ny_train_s = np.ones((X_train_setosa.shape[0], ))\n\nX_test_vv = np.vstack((X_train_versicolor, X_train_virginica))\n\nX_train = np.vstack((X_train_vv, X_train_s))\ny_train = np.hstack((y_train_vv, y_train_s))\n\nX_test = np.vstack((X_test_vv, X_test_s))\ny_test = np.hstack((y_train_

In [5]:

X_train, X_test, y_train, y_test = train_test_split(data[list(range(4))], data[4], test_size=0.2, random_state=None, stratify=data[4])

X_train_setosa = X_train[y_train=='Iris-setosa'].to_numpy()
X_train_versicolor = X_train[y_train=='Iris-versicolor'].to_numpy()
X_train_virginica = X_train[y_train=='Iris-virginica'].to_numpy()

X_test_setosa_v_v = X_test.to_numpy()
y_test_setosa_v_v = (y_test == 'Iris-setosa').astype(int).to_numpy()

X_test_versicolor_virginica = X_test[y_test!='Iris-setosa'].to_numpy()
y_test_versicolor_virginica = (y_test[y_test!='Iris-setosa'] == 'Iris-versicolor').astype(int).to_numpy()

y_train_setosa = np.zeros((X_train_setosa.shape[0], ))
y_train_versicolor = np.ones((X_train_versicolor.shape[0], ))

X_train = np.vstack((X_train_setosa, X_train_versicolor))

y_train = np.hstack((y_train_setosa, y_train_versicolor))

X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, test_size=0.2, random_state=None, stratify=y_train)

In [6]:
def accuracy(labels, predictions):
    return np.mean(labels == predictions)

def heavyside(x):
    return np.where(x > 0, np.ones_like(x), np.zeros_like(x))

def center_data(x):
    return x - np.mean(x, axis=0)

def vector_length(x):
    return np.linalg.norm(x)

class SingleLayerPerceptron():
    def fit(self, x, y, theta):
        x, y = x.copy(), y.copy()
        self.w = np.mean(x[y == 1], axis=0)
        x = center_data(x)
        while True:
            w_prime = self.w 
            random_idx = np.random.randint(low=0, high=x.shape[0], size=(1, ))[0]
            v = x[random_idx]
            scalar = self.w.T @ v
            # v is from P
            if y[random_idx] == 1:
                if scalar > 0:
                    pass
                else:
                    w_prime = self.w + v   
            # v is from N
            else:
                if scalar < 0:
                    pass
                else:
                    w_prime = self.w - v
            if vector_length(self.w - w_prime) < theta:
                self.w = w_prime
                break
            self.w = w_prime
    
    def predict(self, x):
        x = x.copy()
        x = center_data(x)
        return heavyside(x @ self.w)

In [7]:
clf = SingleLayerPerceptron()
clf.fit(X_train, y_train, 0.001)

In [8]:
y_pred = clf.predict(X_test)
y_pred = y_pred.reshape((-1, ))
print(y_pred)

print(accuracy(y_test, y_pred))

[1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1.]
1.0


0.5
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

## Excercise 2. Multilayer-Perceptron (MLP)

In [9]:
class DenseLayer():
    def __init__(self, input_shape, output_shape, activation):
        """
        output_shape is equal to the number of neurons in the layer
        """
        self.w = np.random.uniform(low=-1, high=1, size=(input_shape, output_shape))
        self.b = np.ones((1, output_shape))
        self.activation = activation
        
    def forward(self, x):
        x_t = np.hstack((np.ones((x.shape[0], 1)), x))
        w_t = np.vstack((self.b, self.w))
        return self.activation(x_t @ w_t)

In [10]:
class NeuralNetwork():
    def __init__(self, layers):
        self.layers = layers
        
    def predict(self, x):
        x = x.copy()
        for layer in self.layers:
            x = layer.forward(x)
        return x

layers = []
layers.append(DenseLayer(input_shape=X_train.shape[1], output_shape=64, activation=heavyside))
layers.append(DenseLayer(input_shape=64, output_shape=128, activation=heavyside))
layers.append(DenseLayer(input_shape=128, output_shape=64, activation=heavyside))
layers.append(DenseLayer(input_shape=64, output_shape=1, activation=heavyside))

clf = NeuralNetwork(layers)
y_pred = clf.predict(X_test)

print(y_pred)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]]


In [11]:
X 
z1 = activation(X @ W1) # layer1
z2 = activation(z1 @ W2) # layer2 

NameError: name 'X' is not defined